#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.bashrc
  source ~/.bashrc

echo "Installing git for version control ..."
  brew install git

echo "Installing curl and wget for HTTP requests..."
  brew install curl wget

echo "Installing ack, a good way to search through files ..."
  brew install ack

# echo "Installing tmux, a good way to save project state and switch between projects ..."
#  brew install tmux

# echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
#  brew install qt

